#!/usr/local/bin/lua

function shift_arg() 
    if #arg == 0 then
        return nil
    end
    r = arg[1]
    table.remove(arg, 1)
    return r
end

function print_err(msg, ...)
    io.stderr:write("[ERROR] ", string.format(msg, ...), "\n")
end

function add_timeshift(str, d) 
    time_pattern = "^(%d+):(%d+):(%d+),(%d+)$"
    h, m, s, ms = string.match(str, time_pattern)

    time = tonumber(h) * 60 + tonumber(m)
    time = time * 60 + tonumber(s)
    time = time * 1000 + tonumber(ms)
    time = math.tointeger(time + d)
    if time < 0 then return nil end
    ms = time % 1000
    time = time // 1000
    s = time % 60
    time = time // 60
    m = time % 60
    time = time // 60
    h = time
    assert(h < 100)

    return string.format("%02d:%02d:%02d,%03d", h, m, s, ms)
end

input_path = nil
output_path = nil
timeshift = nil

while true do
    cmd = shift_arg()
    if cmd == nil then
        break
    elseif cmd == "-o" then
        if output_path ~= nil then
            print_err("duplicate '-o' flag")
            os.exit(false)
        end
        output_path = shift_arg()
        if output_path == nil then
            print_err("missing argument after '-o' flag")
            os.exit(false)
        end
    elseif cmd == "-d" then
        -- TODO: allow 'human readable' times (e.g. '5s' gets parsed as 5000 milliseconds)
        time_str = shift_arg()
        timeshift = tonumber(time_str)
        assert(type(timeshift) == "number")
        assert(math.type(timeshift) == "integer")
    else
        if input_path ~= nil then
            print_err("excess argument '%s'", cmd)
            os.exit(false)
        end
        input_path = cmd
    end
end

if timeshift == nil then
    print_err("no timeshift value given")
    os.exit(false)
end

input_file = io.open(input_path, "r")
if io.type(input_file) ~= "file" then
    print_err("Could not open file '%s'", input_path)
    os.exit(false)
end

if output_path == nil then
    name, ext = string.match(input_path, "^(.*)%.(.-)$")
    if name == nil then
        output_path = "out.srt"
    else
        output_path = string.format("%s-out.%s", name, ext)
    end
end
output_file = io.open(output_path, "w")
if io.type(output_file) ~= "file" then
    print_err("Could not open file '%s'", output_path)
    os.exit(false)
end

state = "nr"
for l in input_file:lines("L") do
    if state == "nr" then
        output_file:write(l)
        state = "time"
    elseif state == "time" then
        t1, t2, rest = string.match(l, "^(%g*) %-%-> (%g*)(.*)")

        t1 = add_timeshift(t1, timeshift)
        t2 = add_timeshift(t2, timeshift)
        assert(t1)
        assert(t2)
        -- TODO: account for t1, t2 being nil (in case of timeshift being to big)

        new_l = string.format("%s --> %s%s", t1, t2, rest)
        output_file:write(new_l);
        state = "content"
    elseif state == "content" then
        output_file:write(l)
        if (string.match(l, "^%s*$")) then
            state = "nr"
        end
    else
        error("state was assigned wrong")
    end
end

io.close(output_file)
io.close(input_file)
